services:
  email-notify:
    image: sunqz/email-notify:latest
    container_name: email-notify
    restart: unless-stopped
    ports:
      - "5111:80"
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      - /vol1/1000/docker/email-notify/mysql:/var/lib/mysql
      - /vol1/1000/docker/email-notify/data:/app/server/data
      - /var/run/docker.sock:/var/run/docker.sock
